//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input/PlayerInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputAction"",
    ""maps"": [
        {
            ""name"": ""P1Movement"",
            ""id"": ""3b4849b0-479d-418d-9798-15cef53af744"",
            ""actions"": [
                {
                    ""name"": ""PlayerOneMovement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b761c721-ef54-43eb-b666-c92c82062da5"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Blower1"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4fbac8f0-3fe8-4421-8abb-dd172848f741"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Movement"",
                    ""id"": ""45237e8d-c36f-4043-8d73-6e3482a3b73e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerOneMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6dab7027-41b9-4a73-a6ed-911329d592c3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PlayerController"",
                    ""action"": ""PlayerOneMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""19eae3ee-89bb-4863-91af-c41dd093c250"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PlayerController"",
                    ""action"": ""PlayerOneMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""BlowerAndPowers"",
                    ""id"": ""b7752638-4cea-4007-a0bb-c7adcea4bdaa"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Blower1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""a3160d3a-39bf-464d-ae54-1bd712a7d310"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PlayerController"",
                    ""action"": ""Blower1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""f4e4018c-e8a5-4509-84ea-106b978b1ebc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PlayerController"",
                    ""action"": ""Blower1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""P2Movement"",
            ""id"": ""42be9347-8454-400e-b1c7-8bd176e7433b"",
            ""actions"": [
                {
                    ""name"": ""PlayerTwoMovement"",
                    ""type"": ""Button"",
                    ""id"": ""354f5c63-1776-4da7-a22e-0bca0000cc73"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Blower2"",
                    ""type"": ""Button"",
                    ""id"": ""f71e9401-a795-4424-b58a-b9d6334f468a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Movement"",
                    ""id"": ""a86b9fcc-29eb-4670-85c9-3406f9ed2308"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerTwoMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""b94338d0-fb92-4e8e-ad84-0dbea9c07ca5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PlayerController"",
                    ""action"": ""PlayerTwoMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""ece66b38-05db-4e8f-bed7-1d1725f67dd6"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PlayerController"",
                    ""action"": ""PlayerTwoMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""BlowerAndPowers"",
                    ""id"": ""e3836802-76aa-46b3-b2ef-6162ee4ddd29"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Blower2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""fb1163ae-0315-4dd7-b5c3-4ae3f0cbebe9"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PlayerController"",
                    ""action"": ""Blower2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""10dba7e7-d717-4e37-ba32-3203ead63d56"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";PlayerController"",
                    ""action"": ""Blower2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New Control Scheme"",
            ""bindingGroup"": ""New Control Scheme"",
            ""devices"": []
        },
        {
            ""name"": ""PlayerController"",
            ""bindingGroup"": ""PlayerController"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // P1Movement
        m_P1Movement = asset.FindActionMap("P1Movement", throwIfNotFound: true);
        m_P1Movement_PlayerOneMovement = m_P1Movement.FindAction("PlayerOneMovement", throwIfNotFound: true);
        m_P1Movement_Blower1 = m_P1Movement.FindAction("Blower1", throwIfNotFound: true);
        // P2Movement
        m_P2Movement = asset.FindActionMap("P2Movement", throwIfNotFound: true);
        m_P2Movement_PlayerTwoMovement = m_P2Movement.FindAction("PlayerTwoMovement", throwIfNotFound: true);
        m_P2Movement_Blower2 = m_P2Movement.FindAction("Blower2", throwIfNotFound: true);
    }

    ~@PlayerInputAction()
    {
        UnityEngine.Debug.Assert(!m_P1Movement.enabled, "This will cause a leak and performance issues, PlayerInputAction.P1Movement.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_P2Movement.enabled, "This will cause a leak and performance issues, PlayerInputAction.P2Movement.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // P1Movement
    private readonly InputActionMap m_P1Movement;
    private List<IP1MovementActions> m_P1MovementActionsCallbackInterfaces = new List<IP1MovementActions>();
    private readonly InputAction m_P1Movement_PlayerOneMovement;
    private readonly InputAction m_P1Movement_Blower1;
    public struct P1MovementActions
    {
        private @PlayerInputAction m_Wrapper;
        public P1MovementActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlayerOneMovement => m_Wrapper.m_P1Movement_PlayerOneMovement;
        public InputAction @Blower1 => m_Wrapper.m_P1Movement_Blower1;
        public InputActionMap Get() { return m_Wrapper.m_P1Movement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(P1MovementActions set) { return set.Get(); }
        public void AddCallbacks(IP1MovementActions instance)
        {
            if (instance == null || m_Wrapper.m_P1MovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_P1MovementActionsCallbackInterfaces.Add(instance);
            @PlayerOneMovement.started += instance.OnPlayerOneMovement;
            @PlayerOneMovement.performed += instance.OnPlayerOneMovement;
            @PlayerOneMovement.canceled += instance.OnPlayerOneMovement;
            @Blower1.started += instance.OnBlower1;
            @Blower1.performed += instance.OnBlower1;
            @Blower1.canceled += instance.OnBlower1;
        }

        private void UnregisterCallbacks(IP1MovementActions instance)
        {
            @PlayerOneMovement.started -= instance.OnPlayerOneMovement;
            @PlayerOneMovement.performed -= instance.OnPlayerOneMovement;
            @PlayerOneMovement.canceled -= instance.OnPlayerOneMovement;
            @Blower1.started -= instance.OnBlower1;
            @Blower1.performed -= instance.OnBlower1;
            @Blower1.canceled -= instance.OnBlower1;
        }

        public void RemoveCallbacks(IP1MovementActions instance)
        {
            if (m_Wrapper.m_P1MovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IP1MovementActions instance)
        {
            foreach (var item in m_Wrapper.m_P1MovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_P1MovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public P1MovementActions @P1Movement => new P1MovementActions(this);

    // P2Movement
    private readonly InputActionMap m_P2Movement;
    private List<IP2MovementActions> m_P2MovementActionsCallbackInterfaces = new List<IP2MovementActions>();
    private readonly InputAction m_P2Movement_PlayerTwoMovement;
    private readonly InputAction m_P2Movement_Blower2;
    public struct P2MovementActions
    {
        private @PlayerInputAction m_Wrapper;
        public P2MovementActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlayerTwoMovement => m_Wrapper.m_P2Movement_PlayerTwoMovement;
        public InputAction @Blower2 => m_Wrapper.m_P2Movement_Blower2;
        public InputActionMap Get() { return m_Wrapper.m_P2Movement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(P2MovementActions set) { return set.Get(); }
        public void AddCallbacks(IP2MovementActions instance)
        {
            if (instance == null || m_Wrapper.m_P2MovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_P2MovementActionsCallbackInterfaces.Add(instance);
            @PlayerTwoMovement.started += instance.OnPlayerTwoMovement;
            @PlayerTwoMovement.performed += instance.OnPlayerTwoMovement;
            @PlayerTwoMovement.canceled += instance.OnPlayerTwoMovement;
            @Blower2.started += instance.OnBlower2;
            @Blower2.performed += instance.OnBlower2;
            @Blower2.canceled += instance.OnBlower2;
        }

        private void UnregisterCallbacks(IP2MovementActions instance)
        {
            @PlayerTwoMovement.started -= instance.OnPlayerTwoMovement;
            @PlayerTwoMovement.performed -= instance.OnPlayerTwoMovement;
            @PlayerTwoMovement.canceled -= instance.OnPlayerTwoMovement;
            @Blower2.started -= instance.OnBlower2;
            @Blower2.performed -= instance.OnBlower2;
            @Blower2.canceled -= instance.OnBlower2;
        }

        public void RemoveCallbacks(IP2MovementActions instance)
        {
            if (m_Wrapper.m_P2MovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IP2MovementActions instance)
        {
            foreach (var item in m_Wrapper.m_P2MovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_P2MovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public P2MovementActions @P2Movement => new P2MovementActions(this);
    private int m_NewControlSchemeSchemeIndex = -1;
    public InputControlScheme NewControlSchemeScheme
    {
        get
        {
            if (m_NewControlSchemeSchemeIndex == -1) m_NewControlSchemeSchemeIndex = asset.FindControlSchemeIndex("New Control Scheme");
            return asset.controlSchemes[m_NewControlSchemeSchemeIndex];
        }
    }
    private int m_PlayerControllerSchemeIndex = -1;
    public InputControlScheme PlayerControllerScheme
    {
        get
        {
            if (m_PlayerControllerSchemeIndex == -1) m_PlayerControllerSchemeIndex = asset.FindControlSchemeIndex("PlayerController");
            return asset.controlSchemes[m_PlayerControllerSchemeIndex];
        }
    }
    public interface IP1MovementActions
    {
        void OnPlayerOneMovement(InputAction.CallbackContext context);
        void OnBlower1(InputAction.CallbackContext context);
    }
    public interface IP2MovementActions
    {
        void OnPlayerTwoMovement(InputAction.CallbackContext context);
        void OnBlower2(InputAction.CallbackContext context);
    }
}
